.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "APT\-CACHER\-NG\-PREPARE" "8" "April 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBapt\-cacher\-ng\-prepare\fR \- modifies apt sources list for use with apt\-cacher\-ng
.P
.SH "SYNOPSIS"
\fBapt\-cacher\-ng\-prepare\fR
.SH "Description"
Changes \fB/etc/apt/sources\.list\fR and \fB/etc/apt/sources\.list\.d/*\.list\fR from \fBhttps://\fR to \fBhttp://HTTPS///\fR \.
.SH "Examples"
\fBsudo apt\-cacher\-ng\-prepare\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
