.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "APT\-CACHER\-NG\-UNDO" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBapt\-cacher\-ng\-undo\fR \- modifies apt sources list for use without apt\-cacher\-ng
.P
.SH "SYNOPSIS"
\fBapt\-cacher\-ng\-undo\fR
.SH "Description"
Changes \fB/etc/apt/sources\.list\fR and \fB/etc/apt/sources\.list\.d/*\.list\fR from \fBhttp://HTTPS///\fR to \fBhttps://\fR \.
.SH "Examples"
\fBsudo apt\-cacher\-ng\-undo\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
