.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "GSUDOEDIT" "8" "April 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBgsudoedit\fR \- graphical sudoedit
.P
.SH "SYNOPSIS"
\fBgsudoedit\fR filename
.SH "Description"
Similar to the sudoedit(8) utility but using a graphical editor\.
.P
Wrapper around sudoedit\. Makes invocation of sudoedit easier\. Less to type\.
.P
Requires environment variable \fBVISUAL\fR to be set to a graphical editor such as \fBmousepad\fR\.
.P
Runs:
.P
\fBenv VISUAL="$VISUAL" sudoedit\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
