.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "IPTABLES\-SAVE\-DETERMINISTIC" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBiptables\-save\-deterministic\fR \- wrapper to run \fBiptables\-save\fR with deterministic output
.SH "SYNOPSIS"
\fBiptables\-save\-deterministic\fR [option]s
.SH "DESCRIPTION"
Runs iptables\-save\. Produces deterministic output\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
