.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "REPO\-ADD\-DIST" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBrepo\-add\-dist\fR \- add derivative stable repository
.SH "SYNOPSIS"
\fBrepo\-add\-dist\fR
.SH "Description"
Adds derivative stable repository\.
.P
No frills\.
.P
Use repository\-dist instead\.
.P
\fB/usr/bin/repo\-add\-dist\fR is self\-contained\.
.SH "Examples"
\fBrepo\-add\-dist\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
