.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "UPGRADE\-NONROOT" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBupgrade\-nonroot\fR \- run /usr/bin/apt\-get\-update\-plus dist\-upgrade
.P
.SH "SYNOPSIS"
\fBupgrade\-nonroot\fR
.SH "Description"
Runs \'sudo /usr/bin/apt\-get\-update\-plus dist\-upgrade\'\.
.P
This works passwordless for any user who is a member of group sudo, because of the sudo /etc/sudoers\.d/upgrade\-passwordless configuration snippet\.
.SH "Examples"
upgrade\-nonroot
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
