.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "VIRTUALBOX\-SEND\-SYSRQ" "1" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBvirtualbox\-send\-sysrq\fR \- Send SysRq command to VirtualBox VMs\.
.SH "SYNOPSIS"
\fBvirtualbox\-send\-sysrq VMNAME SysRqCommand\fR
.SH "Description"
Send SysRq command to VirtualBox VMs\.
.P
Has to be used on the host\.
.SH "Examples"
\fBvirtualbox\-send\-sysrq Whonix\-Workstation\-XFCE h\fR
.P
\fBvirtualbox\-send\-sysrq Whonix\-Workstation\-CLI h\fR
.P
\fBvirtualbox\-send\-sysrq Whonix\-Gateway\-XFCE h\fR
.P
\fBvirtualbox\-send\-sysrq Whonix\-Gateway\-CLI h\fR
.P
\fBvirtualbox\-send\-sysrq Kicksecure\-XFCE h\fR
.P
\fBvirtualbox\-send\-sysrq Kicksecure\-CLI h\fR
.SH "Documentation"
https://www\.whonix\.org/wiki/SysRq
.P
https://forums\.whonix\.org/t/send\-sysrq\-commands\-to\-virtualbox\-usability\-helper\-virtualbox\-send\-sysrq/8369
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
