.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WHONIX\-DEV\-BACKUP" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBwhonix\-dev\-backup\fR \- creates a backup of the whonix\.org website and all Whonix source codes
.P
.SH "SYNOPSIS"
\fBwhonix\-dev\-backup\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
