.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WHONIX\-REPO\-ADD" "8" "January 2020" "usability-misc" "usability-misc Manual"
.SH "NAME"
\fBwhonix\-repo\-add\fR \- add Whonix stable repository
.P
.SH "SYNOPSIS"
\fBwhonix\-repo\-add\fR
.SH "Description"
Adds Whonix stable repository\.
.P
No frills\.
.P
Use repository-dist instead\.
.P
\fB/usr/bin/whonix\-repo\-add\fR is self\-contained\.
.SH "Examples"
\fBwhonix\-repo\-add\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
