#!/bin/bash

set -e

source usr/bin/dist-installer-cli

target_user=root

test_file -f /etc/hostname
test_file -d /
test_file -w "$HOME"
test_file -r /
test_file -e /

if ! test_file -f /nonexisting; then
   true OK
else
   exit 1
fi
