#!/bin/sh

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -x /usr/lib/default-editor/default_editor.sh ]; then
   . /usr/lib/default-editor/default_editor.sh
fi
