#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://askubuntu.com/questions/314395/proper-way-to-let-user-enter-password-for-a-bash-script-using-only-the-gui-with

## SUDO_ASKPASS does not pass environment variables.
askpass_title="Authorization required."

zenity \
   --title="$askpass_title" \
   --password
