#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions

## modified based on answer by roaima
## http://unix.stackexchange.com/users/100397/roaima
## http://unix.stackexchange.com/questions/254419/how-to-get-a-deterministic-complete-dump-of-all-iptables-rules

exec iptables-save | sed -e 's/\[[0-9:]*\]/[0,0]/' -e '/^#/d'
