#!/bin/bash

## Copyright (C) 2021 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

if [ "$(id -u)" != "0" ]; then
   echo "ERROR: must be run as root! sudo $0"
   exit 1
fi

sed -i '/OnlyShowIn/d' /etc/xdg/autostart/orca-autostart.desktop

echo "OK"
