#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## Copyright (C) 2019 - 2019 Dipto
## See the file COPYING for copying conditions.

set -e

get_password() {
   ## author of contents of get_password function
   ## Dipto
   ## https://askubuntu.com/users/133486/dipto
   ##
   ## source of contents of get_password function
   ##
   ## https://askubuntu.com/a/299469/389275
   ##
   ## license:
   ## licensed under cc by-sa 3.0 with attribution required.

   unset password
   unset prompt
   while IFS= read -p "$prompt" -r -s -n 1 char
   do
      # Enter - accept password
      if [[ $char == $'\0' ]] ; then
         break
      fi
      # Backspace
      if [[ $char == $'\177' ]] ; then
         prompt=$'\b \b'
         password="${password%?}"
      else
         prompt='*'
         password+="$char"
      fi
   done
}

if [ "$(id -u)" != "0" ]; then
   echo "ERROR: This must be run as root (sudo)!" >&2
   exit 1
fi

adduser_conf_file="$(cat /etc/adduser.conf)"

first_uid="$(
   grep 'FIRST_UID' <<< "${adduser_conf_file}" | grep -v '^\s*#' \
      | cut -d'=' -f2 | sed 's/^[[:space:]]*//'
)"
last_uid="$(
   grep 'LAST_UID' <<< "${adduser_conf_file}" | grep -v '^\s*#' \
      | cut -d'=' -f2 | sed 's/^[[:space:]]*//'
)"
if [ -z "${first_uid}" ]; then
  first_uid=1000
fi
if [ -z "${last_uid}" ]; then
  last_uid=59999
fi

echo "Users present on the system:"
while read -r user_entry; do
   current_uid="$(cut -d':' -f3 <<< "${user_entry}")"
   if [ "${current_uid}" -ge "${first_uid}" ] \
      && [ "${current_uid}" -le "${last_uid}" ]; then
      echo -n '   ';
      cut -d':' -f1 <<< "${user_entry}"
   fi
done < /etc/passwd

read -r -p "Enter the username whose password you want to change: " user

if [ "$user" = "" ]; then
   echo "ERROR: No username provided. Please specify a username." >&2
   exit 1
fi

if ! id "$user" &>/dev/null ; then
   echo "ERROR: User '$user' does not exist. Please check the username and try again." >&2
   exit 1
fi

if [ "$user" = "sysmaint" ]; then
   echo
   echo "If you change the password for the sysmaint account, you will not be"
   echo "automatically logged into the sysmaint session when booting in"
   echo "'PERSISTENT mode SYSMAINT'. To log into the sysmaint session, type"
   echo "'sysmaint' as the user account name, and provide the password you set"
   echo "here."
   echo
fi

echo -n "Enter the new password for user '$user': "
echo
get_password
first_input="$password"
echo

echo -n "Re-enter the new password to confirm: "
echo
get_password
second_input="$password"
echo

if [ ! "$first_input" = "$second_input" ]; then
   echo "ERROR: Passwords do not match. Password has not been changed." >&2
   exit 1
fi

if [ "$first_input" = "" ]; then
   echo "ERROR: No password provided. Please try again." >&2
   exit 1
fi

echo "${user}:${password}" | chpasswd
echo "SUCCESS: Password for user '$user' has been updated successfully."
